# CPP = g++
# CPPFLAGS = -Wall -g -std=c++14

# all : Constants.o

# Constants.o : Constants.h Constants.cc 
# 	$(CPP) $(CPPFLAGS) -c Constants.cc 

# # .PHONY : clean 
# # clean : 
# 	# rm -f *.o core *~